/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Vol;
import model.Escale;
import controller.EscaleDAOController;
import controller.AeroportDAOController;
import model.Aeroport;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;


/**
 *
 * @author CHAWKI
 */
public class AddEscaleUI extends javax.swing.JFrame {
   private Vol vol;
private EscaleDAOController escaleDAO = new EscaleDAOController();
private AeroportDAOController aeroportDAO = new AeroportDAOController();

    /**
     * Creates new form AddEscaleUI
     */
    public AddEscaleUI(Vol vol) {
    this.vol = vol;
    initComponents();
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    cbAeroportEscale.setModel(new javax.swing.DefaultComboBoxModel<Aeroport>());
    setLocationRelativeTo(null);

    // Afficher seulement le nom dans la combo
    cbAeroportEscale.setRenderer(new javax.swing.DefaultListCellRenderer() {
        @Override
        public java.awt.Component getListCellRendererComponent(
                javax.swing.JList<?> list, Object value, int index,
                boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value instanceof Aeroport) {
                Aeroport a = (Aeroport) value;
                setText(a.getNom());
            }
            return this;
        }
    });

    loadAeroports();
}
    private void loadAeroports() {
    cbAeroportEscale.removeAllItems();
    java.util.ArrayList<Aeroport> liste = aeroportDAO.getAll();
    if (liste != null) {
        for (Aeroport a : liste) {
            cbAeroportEscale.addItem(a);
        }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtOrdre = new javax.swing.JSpinner();
        cbAeroportEscale = new javax.swing.JComboBox<>();
        txtHeureArrivee = new javax.swing.JTextField();
        txtHeureDepart = new javax.swing.JTextField();
        btnSaveEscale = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cbAeroportEscale.setToolTipText("");
        cbAeroportEscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAeroportEscaleActionPerformed(evt);
            }
        });

        txtHeureArrivee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHeureArrivee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeureArriveeActionPerformed(evt);
            }
        });

        txtHeureDepart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnSaveEscale.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSaveEscale.setText("Save");
        btnSaveEscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEscaleActionPerformed(evt);
            }
        });

        jLabel1.setText("Aeroport");

        jLabel2.setText("Ordre");

        jLabel3.setText("Heure d 'arrivee");

        jLabel4.setText("Heure de départ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Escale");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHeureArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeureDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAeroportEscale, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrdre, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(btnSaveEscale, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbAeroportEscale, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrdre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeureArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeureDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btnSaveEscale, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        txtOrdre.setModel(
            new javax.swing.SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAeroportEscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAeroportEscaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAeroportEscaleActionPerformed

    private void btnSaveEscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEscaleActionPerformed
   
    String heureArrTxt = txtHeureArrivee.getText().trim();
    String heureDepTxt = txtHeureDepart.getText().trim();
    Object selected = cbAeroportEscale.getSelectedItem();

    if (selected == null || heureArrTxt.isEmpty() || heureDepTxt.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Remplis tous les champs.");
        return;
    }

    Aeroport aeroport = (Aeroport) selected;

    try {
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("HH:mm");
        LocalTime heureArr = LocalTime.parse(heureArrTxt, fmt);
        LocalTime heureDep = LocalTime.parse(heureDepTxt, fmt);

        // Heures du vol (déjà dans ton objet vol)
        LocalTime volDep = vol.getHeureDepart();
        LocalTime volArr = vol.getHeureArrivee();

        // 1) arrivée escale entre départ et arrivée du vol
        if (heureArr.isBefore(volDep) || heureArr.isAfter(volArr)) {
            JOptionPane.showMessageDialog(this,
                "L'heure d'arrivée de l'escale doit être entre l'heure de départ et l'heure d'arrivée du vol.");
            return;
        }

        // 2) départ escale >= arrivée escale
        if (heureDep.isBefore(heureArr)) {
            JOptionPane.showMessageDialog(this,
                "L'heure de départ de l'escale doit être >= à l'heure d'arrivée de l'escale.");
            return;
        }

        // Création et sauvegarde de l'escale
        Escale e = new Escale();
        e.setVol(vol);
        e.setAeroport(aeroport);
        e.setOrdre((int) txtOrdre.getValue());
        e.setHeureArrivee(heureArr);
        e.setHeureDepart(heureDep);

        escaleDAO.save(e);

        JOptionPane.showMessageDialog(this, "Escale ajoutée avec succès.");
        dispose(); // fermer la fenêtre si tu veux

    } catch (DateTimeParseException ex) {
        JOptionPane.showMessageDialog(this,
            "Format d'heure invalide (utilise HH:mm, ex : 12:30).");
    }
       // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveEscaleActionPerformed

    private void txtHeureArriveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeureArriveeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeureArriveeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEscaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEscaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEscaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEscaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveEscale;
    private javax.swing.JComboBox<Aeroport> cbAeroportEscale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtHeureArrivee;
    private javax.swing.JTextField txtHeureDepart;
    private javax.swing.JSpinner txtOrdre;
    // End of variables declaration//GEN-END:variables
}
